var liste_mots = [
  "absinthe",
  "acinier",
  "aconit napel",
  "aigremone",
  "airelle",
  "ajonc",
  "alisier blanc",
  "amarante blette",
  "an\u00e9mone sylvie",
  "argousier",
  "aristoloche",
  "armoise",
  "arroche",
  "arum",
  "asaret",
  "asperge",
  "aub\u00e9pine",
  "aulne",
  "avoine",
  "baguenaudier",
  "ballote",
  "barbar\u00e9e",
  "bardane",
  "benoite",
  "betterave",
  "bl\u00e9",
  "bleuet",
  "bois-joli",
  "boucage",
  "bouillon blanc",
  "bouleau",
  "bourdaine",
  "bourrache",
  "bourse-\u00e0-pasteur",
  "bouton d'or",
  "brome faux-seigle",
  "bruy\u00e8re",
  "bruy\u00e8re a balais",
  "buis",
  "calament",
  "campanule",
  "c\u00e2prier",
  "card\u00e8re",
  "carvi",
  "c\u00e9leri",
  "centaur\u00e9e jac\u00e9e",
  "cerfeuil",
  "chanvre",
  "chardon",
  "chardon \u00e0 foulon",
  "charme",
  "ch\u00e2taigne d'eau",
  "ch\u00e2taignier",
  "ch\u00eane",
  "ch\u00eane tauzin",
  "ch\u00eane vert",
  "ch\u00e9nopode",
  "chervis",
  "ch\u00e8vrefeuille",
  "chicor\u00e9e",
  "chiendent",
  "choin",
  "ciboule",
  "ciboulette sauvage",
  "cigu\u00eb",
  "citron",
  "cl\u00e9matite",
  "cognassier",
  "coquelicot",
  "coqueret",
  "cormier",
  "cornouiller sanguin",
  "cornouiller m\u00e2le",
  "coronille vari\u00e9e",
  "corydale",
  "cranson",
  "cresson",
  "crocus \u00e0 safran",
  "cumin",
  "cuscute",
  "cytise aubour",
  "dauphinelle",
  "digitale",
  "\u00e9chalote",
  "\u00e9picea",
  "\u00e9pine vinette",
  "\u00e9rable",
  "estragon",
  "\u00e9sule",
  "euphorbe",
  "ficaire fausse renoncule",
  "filaire",
  "foug\u00e8re",
  "fragon",
  "fr\u00eane",
  "fusain",
  "gaillet",
  "gaillet gratteron",
  "garance",
  "g\u00e9n\u00e9pi",
  "gen\u00eat",
  "gen\u00eat a balais",
  "gen\u00e9vrier",
  "g\u00e9ranium sauvage",
  "germandr\u00e9e",
  "gesse",
  "gesse aphylle",
  "gesse des bois",
  "gesse tub\u00e9reuse",
  "girofl\u00e9e",
  "gr\u00e9mil",
  "groseiller",
  "gui",
  "haricot",
  "herbe aux verrues",
  "h\u00eatre",
  "houblon",
  "houx",
  "if",
  "inule des montagnes",
  "iris faux-acore",
  "ivraie enivrante",
  "jasmin",
  "jonc",
  "jonquille",
  "laiche",
  "lampourde glouteron",
  "laurier-sauce",
  "lentille cultiv\u00e9e",
  "lierre",
  "lilas",
  "linaire cymbalaire",
  "liseron",
  "marjolaine",
  "massette",
  "mauve",
  "m\u00e9lampyre",
  "m\u00e9l\u00e8ze",
  "m\u00e9lisse",
  "menthe",
  "mercuriale",
  "merisier",
  "millet",
  "morelle",
  "mouron rouge",
  "moutarde des champs",
  "muflier",
  "muguet",
  "myrtille",
  "navet",
  "navette",
  "n\u00e9flier",
  "noisetier",
  "noix de terre",
  "noyer",
  "oignon",
  "orge",
  "origan",
  "orme",
  "orpin",
  "ortie",
  "panais",
  "panic pied-de-coq",
  "panicaut",
  "pas d'\u00e2ne",
  "pens\u00e9e",
  "perruquier",
  "persil",
  "peuplier",
  "pigamon",
  "pimprenelle",
  "pin d'arolle",
  "pin cembro",
  "pin pignon",
  "pissenlit",
  "pivoine",
  "platane",
  "pommier sauvage",
  "populage",
  "potiron",
  "pourpier",
  "pr\u00eale",
  'primev\u00e8re "coucou"',
  "prunellier",
  "prunier",
  "pulsatille",
  "radis",
  "r\u00e9glisse",
  "renou\u00e9e des oiseaux",
  "renou\u00e9e persicaire",
  "r\u00e9s\u00e9da",
  "rhinanthe",
  "romarin",
  "ronce bleue",
  "roseau",
  "rosier",
  "sainfoin",
  "salsifis sauvage",
  "sapin",
  "sarrazin",
  "sauge",
  "saule",
  "saule marsault",
  "sceau de Salomon",
  "seigle",
  "s\u00e9necon",
  "serpolet",
  "sorbier des oiseleurs",
  "souci",
  "sureau",
  "tamier",
  "tanaisie",
  "thym",
  "tilleul",
  "tournesol",
  "tr\u00e8fle",
  "tr\u00e8fle d'eau",
  "tro\u00e8ne",
  "tulipe",
  "val\u00e9riane",
  "verveine officinale",
  "vesce",
  "vigne",
  "viorne mancienne",
  "viorne obier",
];
